### ISSUE TITLE
ModuleNotFoundError: No module named 'tkinter' when installing by pip

### ISSUE THREAD

**Issue by FreePhoenix888** [laggykiller/sticker-convert#102]
```
freephoenix888@FreePhoenix888:~$ pip install sticker-convert
Defaulting to user installation because normal site-packages is not writeable
Collecting sticker-convert
  Downloading sticker_convert-2.2.2-py3-none-any.whl (9.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.8/9.8 MB 868.8 kB/s eta 0:00:00
Collecting python-telegram-bot~=20.5
  Downloading python_telegram_bot-20.7-py3-none-any.whl (552 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 552.6/552.6 KB 835.8 kB/s eta 0:00:00
Collecting pyoxipng~=9.0.0
  Downloading pyoxipng-9.0.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 838.4 kB/s eta 0:00:00
Requirement already satisfied: requests~=2.31.0 in ./.local/lib/python3.10/site-packages (from sticker-convert) (2.31.0)
Collecting webp~=0.3.0
  Downloading webp-0.3.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (403 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 403.6/403.6 KB 851.0 kB/s eta 0:00:00
Collecting apngasm-python~=1.2.1
  Downloading apngasm_python-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (469 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 469.4/469.4 KB 577.7 kB/s eta 0:00:00
Collecting pyav~=12.0.0
  Downloading pyav-12.0.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (27.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.1/27.1 MB 913.9 kB/s eta 0:00:00
Collecting Pillow~=10.1.0
  Downloading Pillow-10.1.0-cp310-cp310-manylinux_2_28_x86_64.whl (3.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.6/3.6 MB 982.1 kB/s eta 0:00:00
Collecting selenium~=4.16.0
  Downloading selenium-4.16.0-py3-none-any.whl (10.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.0/10.0 MB 869.2 kB/s eta 0:00:00
Collecting signalstickers-client~=3.3.0
  Downloading signalstickers_client-3.3.0-py3-none-any.whl (16 kB)
Collecting ttkbootstrap-fork-laggykiller~=1.5.1
  Downloading ttkbootstrap_fork_laggykiller-1.5.1.post1-py3-none-any.whl (112 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 112.5/112.5 KB 923.2 kB/s eta 0:00:00
Collecting tqdm~=4.66.1
  Downloading tqdm-4.66.1-py3-none-any.whl (78 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.3/78.3 KB 1.0 MB/s eta 0:00:00
Collecting rlottie-python~=1.2.1
  Downloading rlottie_python-1.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (877 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 877.8/877.8 KB 928.1 kB/s eta 0:00:00
Collecting rookiepy~=0.3.6
  Downloading rookiepy-0.3.6-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.7/3.7 MB 862.5 kB/s eta 0:00:00
Requirement already satisfied: numpy~=1.26.2 in ./.local/lib/python3.10/site-packages (from sticker-convert) (1.26.2)
Collecting imageio~=2.33.1
  Downloading imageio-2.33.1-py3-none-any.whl (313 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 313.3/313.3 KB 1.1 MB/s eta 0:00:00
Collecting beautifulsoup4~=4.12.2
  Downloading beautifulsoup4-4.12.2-py3-none-any.whl (142 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 143.0/143.0 KB 1.1 MB/s eta 0:00:00
Collecting memory-tempfile~=2.2.3
  Downloading memory_tempfile-2.2.3-py3-none-any.whl (5.7 kB)
Collecting soupsieve>1.2
  Downloading soupsieve-2.5-py3-none-any.whl (36 kB)
Collecting httpx~=0.25.2
  Downloading httpx-0.25.2-py3-none-any.whl (74 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.0/75.0 KB 1.1 MB/s eta 0:00:00
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests~=2.31.0->sticker-convert) (3.3)
Requirement already satisfied: urllib3<3,>=1.21.1 in ./.local/lib/python3.10/site-packages (from requests~=2.31.0->sticker-convert) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests~=2.31.0->sticker-convert) (2020.6.20)
Requirement already satisfied: charset-normalizer<4,>=2 in ./.local/lib/python3.10/site-packages (from requests~=2.31.0->sticker-convert) (3.3.2)
Collecting trio~=0.17
  Downloading trio-0.23.2-py3-none-any.whl (461 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 461.6/461.6 KB 1.1 MB/s eta 0:00:00
Collecting trio-websocket~=0.9
  Downloading trio_websocket-0.11.1-py3-none-any.whl (17 kB)
Collecting certifi>=2017.4.17
  Downloading certifi-2023.11.17-py3-none-any.whl (162 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 162.5/162.5 KB 1.1 MB/s eta 0:00:00
Requirement already satisfied: anyio<4.0.0,>=3.0.0 in ./.local/lib/python3.10/site-packages (from signalstickers-client~=3.3.0->sticker-convert) (3.7.1)
INFO: pip is looking at multiple versions of selenium to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of rookiepy to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of rlottie-python to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of requests to determine which version is compatible with other requirements. This could take a while.
Collecting requests~=2.31.0
  Using cached requests-2.31.0-py3-none-any.whl (62 kB)
INFO: pip is looking at multiple versions of python-telegram-bot to determine which version is compatible with other requirements. This could take a while.
Collecting python-telegram-bot~=20.5
  Downloading python_telegram_bot-20.6-py3-none-any.whl (548 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 548.5/548.5 KB 1.0 MB/s eta 0:00:00
Requirement already satisfied: httpx~=0.25.0 in ./.local/lib/python3.10/site-packages (from python-telegram-bot~=20.5->sticker-convert) (0.25.1)
  Downloading python_telegram_bot-20.5-py3-none-any.whl (544 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 544.8/544.8 KB 914.3 kB/s eta 0:00:00
Collecting httpx~=0.24.1
  Downloading httpx-0.24.1-py3-none-any.whl (75 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 75.4/75.4 KB 1.0 MB/s eta 0:00:00
Requirement already satisfied: cryptography<4.0.0,>=3.1.1 in /usr/lib/python3/dist-packages (from signalstickers-client~=3.3.0->sticker-convert) (3.4.8)
Collecting protobuf<4.0.0,>=3.13.0
  Downloading protobuf-3.20.3-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 1.1 MB/s eta 0:00:00
Collecting httpcore<0.18.0,>=0.15.0
  Downloading httpcore-0.17.3-py3-none-any.whl (74 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 74.5/74.5 KB 1.1 MB/s eta 0:00:00
Requirement already satisfied: sniffio in ./.local/lib/python3.10/site-packages (from httpx~=0.24.1->python-telegram-bot~=20.5->sticker-convert) (1.3.0)
Requirement already satisfied: cffi>=1.0.0 in ./.local/lib/python3.10/site-packages (from webp~=0.3.0->sticker-convert) (1.16.0)
Requirement already satisfied: exceptiongroup in ./.local/lib/python3.10/site-packages (from anyio<4.0.0,>=3.0.0->signalstickers-client~=3.3.0->sticker-convert) (1.1.3)
Requirement already satisfied: pycparser in ./.local/lib/python3.10/site-packages (from cffi>=1.0.0->webp~=0.3.0->sticker-convert) (2.21)
Requirement already satisfied: attrs>=20.1.0 in ./.local/lib/python3.10/site-packages (from trio~=0.17->selenium~=4.16.0->sticker-convert) (23.1.0)
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting outcome
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Collecting wsproto>=0.14
  Downloading wsproto-1.2.0-py3-none-any.whl (24 kB)
Collecting PySocks!=1.5.7,<2.0,>=1.5.6
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Requirement already satisfied: h11<0.15,>=0.13 in ./.local/lib/python3.10/site-packages (from httpcore<0.18.0,>=0.15.0->httpx~=0.24.1->python-telegram-bot~=20.5->sticker-convert) (0.14.0)
Installing collected packages: sortedcontainers, wsproto, tqdm, soupsieve, rookiepy, rlottie-python, PySocks, pyoxipng, pyav, protobuf, Pillow, outcome, memory-tempfile, certifi, apngasm-python, webp, ttkbootstrap-fork-laggykiller, trio, imageio, httpcore, beautifulsoup4, trio-websocket, httpx, signalstickers-client, selenium, python-telegram-bot, sticker-convert
  Attempting uninstall: httpcore
    Found existing installation: httpcore 1.0.2
    Uninstalling httpcore-1.0.2:
      Successfully uninstalled httpcore-1.0.2
  Attempting uninstall: httpx
    Found existing installation: httpx 0.25.1
    Uninstalling httpx-0.25.1:
      Successfully uninstalled httpx-0.25.1
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
duckduckgo-search 3.9.5 requires httpx[brotli,http2,socks]>=0.25.1, but you have httpx 0.24.1 which is incompatible.
Successfully installed Pillow-10.1.0 PySocks-1.7.1 apngasm-python-1.2.1 beautifulsoup4-4.12.2 certifi-2023.11.17 httpcore-0.17.3 httpx-0.24.1 imageio-2.33.1 memory-tempfile-2.2.3 outcome-1.3.0.post0 protobuf-3.20.3 pyav-12.0.2 pyoxipng-9.0.0 python-telegram-bot-20.5 rlottie-python-1.2.1 rookiepy-0.3.6 selenium-4.16.0 signalstickers-client-3.3.0 sortedcontainers-2.4.0 soupsieve-2.5 sticker-convert-2.2.2 tqdm-4.66.1 trio-0.23.2 trio-websocket-0.11.1 ttkbootstrap-fork-laggykiller-1.5.1.post1 webp-0.3.0 wsproto-1.2.0
freephoenix888@FreePhoenix888:~$ python -m sticker_convert
Command 'python' not found, did you mean:
  command 'python3' from deb python3
  command 'python' from deb python-is-python3
freephoenix888@FreePhoenix888:~$ python3 -m sticker_convert
sticker-convert 2.2.2
Launching GUI...
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/freephoenix888/.local/lib/python3.10/site-packages/sticker_convert/__main__.py", line 26, in <module>
    main()
  File "/home/freephoenix888/.local/lib/python3.10/site-packages/sticker_convert/__main__.py", line 16, in main
    from sticker_convert.gui import GUI  # type: ignore
  File "/home/freephoenix888/.local/lib/python3.10/site-packages/sticker_convert/gui.py", line 16, in <module>
    from ttkbootstrap import Window, StringVar, BooleanVar, IntVar # type: ignore
  File "/home/freephoenix888/.local/lib/python3.10/site-packages/ttkbootstrap/__init__.py", line 1, in <module>
    from ttkbootstrap.style import Style
  File "/home/freephoenix888/.local/lib/python3.10/site-packages/ttkbootstrap/style.py", line 3, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'
freephoenix888@FreePhoenix888:~$ sticker-convert
sticker-convert 2.2.2
Launching GUI...
Traceback (most recent call last):
  File "/home/freephoenix888/.local/bin/sticker-convert", line 8, in <module>
    sys.exit(main())
  File "/home/freephoenix888/.local/lib/python3.10/site-packages/sticker_convert/__main__.py", line 16, in main
    from sticker_convert.gui import GUI  # type: ignore
  File "/home/freephoenix888/.local/lib/python3.10/site-packages/sticker_convert/gui.py", line 16, in <module>
    from ttkbootstrap import Window, StringVar, BooleanVar, IntVar # type: ignore
  File "/home/freephoenix888/.local/lib/python3.10/site-packages/ttkbootstrap/__init__.py", line 1, in <module>
    from ttkbootstrap.style import Style
  File "/home/freephoenix888/.local/lib/python3.10/site-packages/ttkbootstrap/style.py", line 3, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

```

**Comment by laggykiller** [comment]
Seems like you are using debian-based distro. Normally tkinter is installed along with python (e.g. Windows, MacOS). However the components of python are installed separately in most linux distribution. Hence you need to install tkinter by `sudo apt install python3-tk`.
