### ISSUE TITLE
macOS 14 FileExistsError

### ISSUE THREAD

**Issue by sindastra** [laggykiller/sticker-convert#111]
Sometimes on macOS 14, clicking on the "Start" button will result in an instant crash.

I'm not sure why this would happen, since the folder is newly created when hitting "Start". Even though the folder stickers_output is empty. Input source is Telegram, output source is Signal.

I already tried deleting all files in stickers_input and stickers_output and restarting the application.

```
sticker-convert 2.2.6
Launching GUI...
Moving old files in input directory to /Users/nat/Desktop/stickers_output/archive_2024-28-01_23-23-10 as input source is not local
Moving old files in output directory to /Users/nat/Desktop/stickers_output/archive_2024-28-01_23-23-10
Exception in thread Thread-1 (start_process):
Traceback (most recent call last):
  File "/Applications/sticker-convert.app/Contents/MacOS/threading.py", line 1045, in _bootstrap_inner
  File "/Applications/sticker-convert.app/Contents/MacOS/threading.py", line 982, in run
  File "/Applications/sticker-convert.app/Contents/MacOS/sticker_convert/gui.py", line 434, in start_process
  File "/Applications/sticker-convert.app/Contents/MacOS/sticker_convert/job.py", line 76, in start
  File "/Applications/sticker-convert.app/Contents/MacOS/sticker_convert/job.py", line 231, in cleanup
  File "<frozen os>", line 225, in makedirs
FileExistsError: [Errno 17] File exists: '/Users/nat/Desktop/stickers_output/archive_2024-28-01_23-23-10'
```

**Comment by laggykiller** [comment]
Are you setting input directory and output directory to the same directory? Please set them as different directory.

**Comment by sindastra** [comment]
Ah, you are correct! I think this shows it is time for me to go to bed... Apologies for the redundant issue!

**Comment by laggykiller** [comment]
Done
