### ISSUE TITLE
macOS 14 shutil.SameFileError

### ISSUE THREAD

**Issue by sindastra** [laggykiller/sticker-convert#112]
Sometimes in macOS 14, converting stickers will download everything successfully and then result in a crash of `shutil.SameFileError`:

Input was set to Telegram, output to Signal.

```
sticker-convert 2.2.6
Launching GUI...
Skip moving old files in input directory as input source is empty
Skip moving old files in output directory as output source is empty
Downloading...
Downloaded 000.webm
Downloaded 001.webm
Downloaded 002.webm
Downloaded 003.webm
Downloaded 004.webm
Downloaded 005.webm
Downloaded 006.webm
Downloaded 007.webm
Downloaded 008.webm
Downloaded 009.webm
Downloaded 010.webm
Downloaded 011.webm
Downloaded 012.webm
Downloaded 013.webm
Downloaded 014.webm
Downloaded 015.webm
Downloaded 016.webm
Downloaded 017.webm
Downloaded 018.webm
Downloaded 019.webm
Downloaded 020.webm
Downloaded 021.webm
Downloaded 022.webm
Downloaded 023.webm
Downloaded 024.webm
Downloaded 025.webm
Downloaded 026.webm
Downloaded 027.webm
Downloaded 028.webm
Downloaded 029.webm
Downloaded 030.webm
Downloaded 031.webm
Downloaded 032.webm
Downloaded 033.webm
Downloaded 034.webm
Downloaded 035.webm
Downloaded 036.webm
Downloaded 037.webm
Downloaded 038.webm
Downloaded 039.webm
Downloaded 040.webm
Downloaded 041.webm
Downloaded 042.webm
Downloaded 043.webm
Downloaded 044.webm
100%|███████████████████████████████████████████████████████████████| 45/45 [00:03<00:00, 11.74it/s]
Exception in thread Thread-1 (start_process):
Traceback (most recent call last):
  File "/Applications/sticker-convert.app/Contents/MacOS/threading.py", line 1045, in _bootstrap_inner
  File "/Applications/sticker-convert.app/Contents/MacOS/threading.py", line 982, in run
  File "/Applications/sticker-convert.app/Contents/MacOS/sticker_convert/gui.py", line 434, in start_process
  File "/Applications/sticker-convert.app/Contents/MacOS/sticker_convert/job.py", line 76, in start
  File "/Applications/sticker-convert.app/Contents/MacOS/sticker_convert/job.py", line 305, in compress
  File "/Applications/sticker-convert.app/Contents/MacOS/shutil.py", line 419, in copy
  File "/Applications/sticker-convert.app/Contents/MacOS/shutil.py", line 236, in copyfile
shutil.SameFileError: '/Users/nat/Desktop/stickers_output/emoji.txt' and '/Users/nat/Desktop/stickers_output/emoji.txt' are the same file
```

**Comment by sindastra** [comment]
I suspect this was caused by the same reason as in #111, so I will close this for now.
