### ISSUE TITLE
Colab errors

### ISSUE THREAD

**Issue by carmenchui** [laggykiller/sticker-convert#119]
In the Colab notebook, the following error appears trying to convert a LINE sticker to a WhatsApp sticker pack:

`b'sticker-convert.py: error: unrecognized arguments: --quantize_method imagequant\n'
`

The sticker pack info I used:

- LINE sticker id: 30270

Also the following fields in the notebook produce float errors:
```
Power ('Importance') of FPS (At least -1. Power lower = More importance)
fps_power:
-0.5
Form field type "float" is not supported
Power ('Importance') of resolution (At least -1. Power lower = More importance)
res_power:
3.0
Form field type "float" is not supported
Power ('Importance') of quality (At least -1. Power lower = More importance)
quality_power:
5.0
Form field type "float" is not supported
Power ('Importance') of color (At least -1. Power lower = More importance)
color_power:
3.0
Form field type "float" is not supported
```

**Comment by laggykiller** [comment]
Thanks for your report. Should be fixed now.

**Comment by carmenchui** [comment]
New error message:

I used this LINE sticker pack: https://store.line.me/stickershop/product/13933497/
Changed the settings in the notebook to output a WhatsApp Sticker pack.

```
/content
['/content/sticker-convert', '--no-confirm', '--input-dir', '/content/drive/MyDrive/stickers_input', '--download-line', '13933497', '--output-dir', '/content/drive/MyDrive/stickers_output', '--export-whatsapp', '--preset', 'auto', '--scale-filter', 'lanczos', '--quantize-method', 'imagequant', '--title', 'Corgi Dog KaKa - CNY Big Stickers', '--author', 'Corgi Dog KaKa - CNY Big Stickers']
sticker-convert 2.6.2

Auto compression option set to whatsapp

Traceback (most recent call last):

  File "/tmp/.mount_sticke6zhn21/usr/src/sticker-convert.py", line 5, in <module>

    main()

  File "/tmp/.mount_sticke6zhn21/usr/src/sticker_convert/__main__.py", line 18, in main

    CLI().cli()

  File "/tmp/.mount_sticke6zhn21/usr/src/sticker_convert/cli.py", line 171, in cli

    self.opt_cred = self.get_opt_cred(args)

                    ^^^^^^^^^^^^^^^^^^^^^^^

  File "/tmp/.mount_sticke6zhn21/usr/src/sticker_convert/cli.py", line 379, in get_opt_cred

    creds = JsonManager.load_json(creds_path)

            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/tmp/.mount_sticke6zhn21/usr/src/sticker_convert/utils/files/json_manager.py", line 11, in load_json

    raise RuntimeError(f"{path} cannot be found")

RuntimeError: /content/creds.json cannot be found
```

**Comment by laggykiller** [comment]
Thanks for report, please try again now

**Comment by carmenchui** [comment]
@laggykiller  The code runs and compiles properly on Colab but the .wasticker pack is empty. 

The full output:

```
/content
['/content/sticker-convert', '--no-confirm', '--input-dir', '/content/drive/MyDrive/stickers_input', '--download-line', '13933497', '--output-dir', '/content/drive/MyDrive/stickers_output', '--export-whatsapp', '--preset', 'auto', '--scale-filter', 'lanczos', '--quantize-method', 'imagequant', '--title', 'Corgi Dog KaKa - CNY Big Stickers', '--author', 'Corgi Dog KaKa - CNY Big Stickers']
sticker-convert 2.6.3

Auto compression option set to whatsapp

Moving old files in input directory to /content/drive/MyDrive/stickers_input/archive_2024-08-02_05-38-46 as input source is not local

Moving old files in output directory to /content/drive/MyDrive/stickers_output/archive_2024-08-02_05-38-46

Downloading...

Downloading https://stickershop.line-scdn.net/stickershop/v1/product/13933497/iphone/stickers@2x.zip

37it [00:00, 107.40it/s]

Downloaded https://stickershop.line-scdn.net/stickershop/v1/product/13933497/iphone/stickers@2x.zip

Unzipping...

Read 366913958@2x.png

Read 366913959@2x.png

Read 366913960@2x.png

Read 366913961@2x.png

Read 366913962@2x.png

Read 366913963@2x.png

Read 366913964@2x.png

Read 366913965@2x.png

Read 366913966@2x.png

Read 366913967@2x.png

Read 366913968@2x.png

Read 366913969@2x.png

Read 366913970@2x.png

Read 366913971@2x.png

Read 366913972@2x.png

Read 366913973@2x.png

Read 366913974@2x.png

Read 366913975@2x.png

Read 366913976@2x.png

Read 366913977@2x.png

Read 366913978@2x.png

Read 366913979@2x.png

Read 366913980@2x.png

Read 366913981@2x.png

Compressing...

[I] Start compressing 000.png -> 000.webp

[C] Compressing 000.png -> 000.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 000.png -> 000.webp but size 17676 < limit 100000, recompressing

[C] Compressing 000.png -> 000.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 000.png -> 000.webp but size 21266 < limit 100000, recompressing

[C] Compressing 000.png -> 000.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 000.png -> 000.webp but size 26882 < limit 100000, recompressing

[C] Compressing 000.png -> 000.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 000.png -> 000.webp but size 30812 < limit 100000, recompressing

[C] Compressing 000.png -> 000.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 001.png -> 001.webp

[C] Compressing 001.png -> 001.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 001.png -> 001.webp but size 26234 < limit 100000, recompressing

[C] Compressing 001.png -> 001.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 001.png -> 001.webp but size 29908 < limit 100000, recompressing

[C] Compressing 001.png -> 001.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 001.png -> 001.webp but size 35740 < limit 100000, recompressing

[C] Compressing 001.png -> 001.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 001.png -> 001.webp but size 39732 < limit 100000, recompressing

[C] Compressing 001.png -> 001.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 002.png -> 002.webp

[C] Compressing 002.png -> 002.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 002.png -> 002.webp but size 26560 < limit 100000, recompressing

[C] Compressing 002.png -> 002.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 002.png -> 002.webp but size 29496 < limit 100000, recompressing

[C] Compressing 002.png -> 002.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 002.png -> 002.webp but size 34852 < limit 100000, recompressing

[C] Compressing 002.png -> 002.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 002.png -> 002.webp but size 38416 < limit 100000, recompressing

[C] Compressing 002.png -> 002.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 003.png -> 003.webp

[C] Compressing 003.png -> 003.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 003.png -> 003.webp but size 21538 < limit 100000, recompressing

[C] Compressing 003.png -> 003.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 003.png -> 003.webp but size 24040 < limit 100000, recompressing

[C] Compressing 003.png -> 003.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 003.png -> 003.webp but size 28406 < limit 100000, recompressing

[C] Compressing 003.png -> 003.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 003.png -> 003.webp but size 31482 < limit 100000, recompressing

[C] Compressing 003.png -> 003.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 004.png -> 004.webp

[C] Compressing 004.png -> 004.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 004.png -> 004.webp but size 22516 < limit 100000, recompressing

[C] Compressing 004.png -> 004.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 004.png -> 004.webp but size 26062 < limit 100000, recompressing

[C] Compressing 004.png -> 004.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 004.png -> 004.webp but size 31876 < limit 100000, recompressing

[C] Compressing 004.png -> 004.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 004.png -> 004.webp but size 35776 < limit 100000, recompressing

[C] Compressing 004.png -> 004.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 005.png -> 005.webp

[C] Compressing 005.png -> 005.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 005.png -> 005.webp but size 20992 < limit 100000, recompressing

[C] Compressing 005.png -> 005.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 005.png -> 005.webp but size 23788 < limit 100000, recompressing

[C] Compressing 005.png -> 005.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 005.png -> 005.webp but size 28630 < limit 100000, recompressing

[C] Compressing 005.png -> 005.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 005.png -> 005.webp but size 31848 < limit 100000, recompressing

[C] Compressing 005.png -> 005.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 006.png -> 006.webp

[C] Compressing 006.png -> 006.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 006.png -> 006.webp but size 17596 < limit 100000, recompressing

[C] Compressing 006.png -> 006.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 006.png -> 006.webp but size 21562 < limit 100000, recompressing

[C] Compressing 006.png -> 006.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 006.png -> 006.webp but size 28072 < limit 100000, recompressing

[C] Compressing 006.png -> 006.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 006.png -> 006.webp but size 32856 < limit 100000, recompressing

[C] Compressing 006.png -> 006.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 007.png -> 007.webp

[C] Compressing 007.png -> 007.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 007.png -> 007.webp but size 24386 < limit 100000, recompressing

[C] Compressing 007.png -> 007.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 007.png -> 007.webp but size 27842 < limit 100000, recompressing

[C] Compressing 007.png -> 007.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 007.png -> 007.webp but size 33902 < limit 100000, recompressing

[C] Compressing 007.png -> 007.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 007.png -> 007.webp but size 37868 < limit 100000, recompressing

[C] Compressing 007.png -> 007.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 008.png -> 008.webp

[C] Compressing 008.png -> 008.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 008.png -> 008.webp but size 18668 < limit 100000, recompressing

[C] Compressing 008.png -> 008.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 008.png -> 008.webp but size 21430 < limit 100000, recompressing

[C] Compressing 008.png -> 008.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 008.png -> 008.webp but size 26264 < limit 100000, recompressing

[C] Compressing 008.png -> 008.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 008.png -> 008.webp but size 29438 < limit 100000, recompressing

[C] Compressing 008.png -> 008.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 009.png -> 009.webp

[C] Compressing 009.png -> 009.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 009.png -> 009.webp but size 23990 < limit 100000, recompressing

[C] Compressing 009.png -> 009.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 009.png -> 009.webp but size 26570 < limit 100000, recompressing

[C] Compressing 009.png -> 009.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 009.png -> 009.webp but size 31498 < limit 100000, recompressing

[C] Compressing 009.png -> 009.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 009.png -> 009.webp but size 34522 < limit 100000, recompressing

[C] Compressing 009.png -> 009.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 010.png -> 010.webp

[C] Compressing 010.png -> 010.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 010.png -> 010.webp but size 19928 < limit 100000, recompressing

[C] Compressing 010.png -> 010.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 010.png -> 010.webp but size 21952 < limit 100000, recompressing

[C] Compressing 010.png -> 010.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 010.png -> 010.webp but size 25672 < limit 100000, recompressing

[C] Compressing 010.png -> 010.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 010.png -> 010.webp but size 28038 < limit 100000, recompressing

[C] Compressing 010.png -> 010.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 011.png -> 011.webp

[C] Compressing 011.png -> 011.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 011.png -> 011.webp but size 19164 < limit 100000, recompressing

[C] Compressing 011.png -> 011.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 011.png -> 011.webp but size 21176 < limit 100000, recompressing

[C] Compressing 011.png -> 011.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 011.png -> 011.webp but size 24728 < limit 100000, recompressing

[C] Compressing 011.png -> 011.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 011.png -> 011.webp but size 26934 < limit 100000, recompressing

[C] Compressing 011.png -> 011.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 012.png -> 012.webp

[C] Compressing 012.png -> 012.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 012.png -> 012.webp but size 35434 < limit 100000, recompressing

[C] Compressing 012.png -> 012.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 012.png -> 012.webp but size 39454 < limit 100000, recompressing

[C] Compressing 012.png -> 012.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 012.png -> 012.webp but size 45982 < limit 100000, recompressing

[C] Compressing 012.png -> 012.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 012.png -> 012.webp but size 50642 < limit 100000, recompressing

[C] Compressing 012.png -> 012.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 013.png -> 013.webp

[C] Compressing 013.png -> 013.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 013.png -> 013.webp but size 16320 < limit 100000, recompressing

[C] Compressing 013.png -> 013.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 013.png -> 013.webp but size 18506 < limit 100000, recompressing

[C] Compressing 013.png -> 013.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 013.png -> 013.webp but size 22310 < limit 100000, recompressing

[C] Compressing 013.png -> 013.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 013.png -> 013.webp but size 24708 < limit 100000, recompressing

[C] Compressing 013.png -> 013.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 014.png -> 014.webp

[C] Compressing 014.png -> 014.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 014.png -> 014.webp but size 21124 < limit 100000, recompressing

[C] Compressing 014.png -> 014.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 014.png -> 014.webp but size 23284 < limit 100000, recompressing

[C] Compressing 014.png -> 014.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 014.png -> 014.webp but size 27016 < limit 100000, recompressing

[C] Compressing 014.png -> 014.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 014.png -> 014.webp but size 29530 < limit 100000, recompressing

[C] Compressing 014.png -> 014.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 015.png -> 015.webp

[C] Compressing 015.png -> 015.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 015.png -> 015.webp but size 22690 < limit 100000, recompressing

[C] Compressing 015.png -> 015.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 015.png -> 015.webp but size 24752 < limit 100000, recompressing

[C] Compressing 015.png -> 015.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 015.png -> 015.webp but size 28452 < limit 100000, recompressing

[C] Compressing 015.png -> 015.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 015.png -> 015.webp but size 31130 < limit 100000, recompressing

[C] Compressing 015.png -> 015.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 016.png -> 016.webp

[C] Compressing 016.png -> 016.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 016.png -> 016.webp but size 17234 < limit 100000, recompressing

[C] Compressing 016.png -> 016.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 016.png -> 016.webp but size 19434 < limit 100000, recompressing

[C] Compressing 016.png -> 016.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 016.png -> 016.webp but size 23326 < limit 100000, recompressing

[C] Compressing 016.png -> 016.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 016.png -> 016.webp but size 25994 < limit 100000, recompressing

[C] Compressing 016.png -> 016.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 017.png -> 017.webp

[C] Compressing 017.png -> 017.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 017.png -> 017.webp but size 18566 < limit 100000, recompressing

[C] Compressing 017.png -> 017.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 017.png -> 017.webp but size 21046 < limit 100000, recompressing

[C] Compressing 017.png -> 017.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 017.png -> 017.webp but size 25440 < limit 100000, recompressing

[C] Compressing 017.png -> 017.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 017.png -> 017.webp but size 28528 < limit 100000, recompressing

[C] Compressing 017.png -> 017.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 018.png -> 018.webp

[C] Compressing 018.png -> 018.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 018.png -> 018.webp but size 21062 < limit 100000, recompressing

[C] Compressing 018.png -> 018.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 018.png -> 018.webp but size 22308 < limit 100000, recompressing

[C] Compressing 018.png -> 018.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 018.png -> 018.webp but size 24686 < limit 100000, recompressing

[C] Compressing 018.png -> 018.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 018.png -> 018.webp but size 26362 < limit 100000, recompressing

[C] Compressing 018.png -> 018.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 019.png -> 019.webp

[C] Compressing 019.png -> 019.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 019.png -> 019.webp but size 14010 < limit 100000, recompressing

[C] Compressing 019.png -> 019.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 019.png -> 019.webp but size 15748 < limit 100000, recompressing

[C] Compressing 019.png -> 019.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 019.png -> 019.webp but size 18458 < limit 100000, recompressing

[C] Compressing 019.png -> 019.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 019.png -> 019.webp but size 20520 < limit 100000, recompressing

[C] Compressing 019.png -> 019.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

100%|██████████| 24/24 [00:11<00:00,  2.53it/s][I] Start compressing 020.png -> 020.webp

[C] Compressing 020.png -> 020.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 020.png -> 020.webp but size 14930 < limit 100000, recompressing

[C] Compressing 020.png -> 020.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 020.png -> 020.webp but size 17546 < limit 100000, recompressing

[C] Compressing 020.png -> 020.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 020.png -> 020.webp but size 21880 < limit 100000, recompressing

[C] Compressing 020.png -> 020.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 020.png -> 020.webp but size 24916 < limit 100000, recompressing

[C] Compressing 020.png -> 020.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 021.png -> 021.webp

[C] Compressing 021.png -> 021.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 021.png -> 021.webp but size 14870 < limit 100000, recompressing

[C] Compressing 021.png -> 021.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 021.png -> 021.webp but size 17572 < limit 100000, recompressing

[C] Compressing 021.png -> 021.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 021.png -> 021.webp but size 21518 < limit 100000, recompressing

[C] Compressing 021.png -> 021.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 021.png -> 021.webp but size 24222 < limit 100000, recompressing

[C] Compressing 021.png -> 021.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 022.png -> 022.webp

[C] Compressing 022.png -> 022.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 022.png -> 022.webp but size 19564 < limit 100000, recompressing

[C] Compressing 022.png -> 022.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 022.png -> 022.webp but size 22214 < limit 100000, recompressing

[C] Compressing 022.png -> 022.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 022.png -> 022.webp but size 26998 < limit 100000, recompressing

[C] Compressing 022.png -> 022.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 022.png -> 022.webp but size 30050 < limit 100000, recompressing

[C] Compressing 022.png -> 022.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

[I] Start compressing 023.png -> 023.webp

[C] Compressing 023.png -> 023.webp res=512x512, quality=11, fps=1, color=46 (step 0-8-16)

[<] Compressed 023.png -> 023.webp but size 14134 < limit 100000, recompressing

[C] Compressing 023.png -> 023.webp res=512x512, quality=25, fps=1, color=103 (step 0-4-8)

[<] Compressed 023.png -> 023.webp but size 16938 < limit 100000, recompressing

[C] Compressing 023.png -> 023.webp res=512x512, quality=48, fps=1, color=164 (step 0-2-4)

[<] Compressed 023.png -> 023.webp but size 21626 < limit 100000, recompressing

[C] Compressing 023.png -> 023.webp res=512x512, quality=68, fps=1, color=206 (step 0-1-2)

[<] Compressed 023.png -> 023.webp but size 24726 < limit 100000, recompressing

[C] Compressing 023.png -> 023.webp res=512x512, quality=95, fps=1, color=257 (step 0-0-1)

100%|██████████| 24/24 [00:11<00:00,  2.02it/s]

Exporting...

Exporting...

Verifying /content/drive/MyDrive/stickers_output/000.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/001.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/002.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/003.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/004.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/005.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/006.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/007.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/008.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/009.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/010.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/011.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/012.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/013.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/014.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/015.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/016.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/017.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/018.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/019.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/020.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/021.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/022.webp for compressing into .wastickers

Verifying /content/drive/MyDrive/stickers_output/023.webp for compressing into .wastickers

[I] Start compressing 000.webp -> 100.png

[C] Compressing 000.webp -> 100.png res=96x96, quality=95, fps=0, color=257 (step 0-0-1)

/content/drive/MyDrive/stickers_output/Corgi Dog KaKa - CNY Big Stickers.wastickers

##########

Summary:

##########



Export results:

/content/drive/MyDrive/stickers_output/Corgi Dog KaKa - CNY Big Stickers.wastickers

```

**Comment by laggykiller** [comment]
Personally tested it, should be working now, please check

**Comment by carmenchui** [comment]
@laggykiller Hi, it works fine now.  Thank you for the quick fixes!!
