### ISSUE TITLE
Error converting a Sticker pack to signal

### ISSUE THREAD

**Issue by HyperCriSiS** [laggykiller/sticker-convert#129]
Hi,

in this Sticker pack, one image cannot be compressed enough:

https://signal.art/addstickers/#pack_id=884c5bc8e034763638038719004b53b6&pack_key=c33df578c4b68331cdefce3cef0b4ad3641ba91cbb9b45816ca82fd38097d20a

Error message:
[F] Failed Compression 020.webp -> 020.apng, cannot get below limit 300000 with lowest quality under current settings (Best size: 544071)

The pack is not uploaded afterwards.

Thanks and regards
Hyper

**Comment by laggykiller** [comment]
Please try v2.7.1

**Comment by HyperCriSiS** [comment]
This is throwing an error:

##### EXCEPTION #####
Function: <compiled_function UploadSignal.start at 0x00000229BCDBD940>
Arguments: [OutputOption(option='signal', dir=WindowsPath('C:/Users/HyperCriSiS/Desktop/sticker-convert/stickers_output'), title='Little Fuck Fuck', author='Hyper'), CompOption(preset='signal', size_max_img=300000, size_max_vid=300000, format_img=['.png'], format_vid=['.apng'], fps_min=1, fps_max=30, fps_power=-0.5, res_w_min=64, res_w_max=512, res_h_min=64, res_h_max=512, res_power=3.0, quality_min=10, quality_max=95, quality_power=5.0, color_min=32, color_max=257, color_power=3.0, duration_min=0, duration_max=3000, steps=16, fake_vid=False, quantize_method='imagequant', scale_filter='lanczos', cache_dir=None, default_emoji='😀', no_compress=False, processes=8, animated=None, square=None), 'CredOption(REDACTED)']
Traceback (most recent call last):
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\cryptography\utils.py", line 34, in _check_byteslike
TypeError: memoryview: a bytes-like object is required, not 'WindowsPath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\sticker_convert\job.py", line 136, in worker
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\sticker_convert\uploaders\upload_signal.py", line 181, in start
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\sticker_convert\uploaders\upload_signal.py", line 149, in upload_stickers_signal
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\anyio\_core\_eventloop.py", line 68, in run
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\anyio\_backends\_asyncio.py", line 204, in run
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\asyncio\runners.py", line 190, in run
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\asyncio\runners.py", line 118, in run
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\asyncio\base_events.py", line 654, in run_until_complete
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\anyio\_backends\_asyncio.py", line 199, in wrapper
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\sticker_convert\uploaders\upload_signal.py", line 47, in upload_pack
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\signalstickers_client\stickersclient.py", line 70, in upload_pack
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\signalstickers_client\classes\uploader.py", line 66, in upload_pack
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\signalstickers_client\classes\signalcrypto.py", line 21, in encrypt
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\cryptography\hazmat\primitives\padding.py", line 125, in update
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\cryptography\hazmat\primitives\padding.py", line 42, in _byte_padding_update
  File "C:\Users\HYPERC~1\Desktop\STICKE~1\cryptography\utils.py", line 36, in _check_byteslike
TypeError: data must be bytes-like
#####################
An error occured while exporting stickers
An error occured during this run.

**Comment by HyperCriSiS** [comment]
Also many fail with similiar message: 
[F] Failed Compression 004.apng -> bytes.apng, cannot get below limit 300000 with lowest quality under current settings (Best size: 6995979)

**Comment by laggykiller** [comment]
Please try v2.7.2

**Comment by laggykiller** [comment]
No reply. Should be fixed. Closing.
