### ISSUE TITLE
Docker run with error : TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'

### ISSUE THREAD

**Issue by hydehk** [laggykiller/sticker-convert#158]
I am using windows 11 with docker GUI
Running (GUI)
```
docker run -d -it --name sticker-convert \
    -v /path/to/your/stickers_input:/app/stickers_input \
    -v /path/to/your/stickers_output:/app/stickers_output \
    -p 5800:5800 \ # Port for Web UI
    -p 5900:5900 \ # Optional for VNC
    laggykiller/sticker-convert:latest
```

```
2024-05-31 16:51:08 [init        ] container is starting...
2024-05-31 16:51:08 [cont-env    ] loading container environment variables...
2024-05-31 16:51:08 [cont-env    ] APP_NAME: loading...
2024-05-31 16:51:08 [cont-env    ] DISPLAY: executing...
2024-05-31 16:51:08 [cont-env    ] DISPLAY: terminated successfully.
2024-05-31 16:51:08 [cont-env    ] DISPLAY: loading...
2024-05-31 16:51:08 [cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
2024-05-31 16:51:08 [cont-env    ] GTK2_RC_FILES: executing...
2024-05-31 16:51:08 [cont-env    ] GTK2_RC_FILES: terminated successfully.
2024-05-31 16:51:08 [cont-env    ] GTK2_RC_FILES: loading...
2024-05-31 16:51:08 [cont-env    ] GTK_THEME: executing...
2024-05-31 16:51:08 [cont-env    ] GTK_THEME: terminated successfully.
2024-05-31 16:51:08 [cont-env    ] GTK_THEME: loading...
2024-05-31 16:51:08 [cont-env    ] HOME: loading...
2024-05-31 16:51:08 [cont-env    ] QT_STYLE_OVERRIDE: executing...
2024-05-31 16:51:08 [cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
2024-05-31 16:51:08 [cont-env    ] QT_STYLE_OVERRIDE: loading...
2024-05-31 16:51:08 [cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
2024-05-31 16:51:08 [cont-env    ] XDG_CACHE_HOME: loading...
2024-05-31 16:51:08 [cont-env    ] XDG_CONFIG_HOME: loading...
2024-05-31 16:51:08 [cont-env    ] XDG_DATA_HOME: loading...
2024-05-31 16:51:08 [cont-env    ] XDG_RUNTIME_DIR: loading...
2024-05-31 16:51:08 [cont-env    ] XDG_STATE_HOME: loading...
2024-05-31 16:51:08 [cont-env    ] container environment variables initialized.
2024-05-31 16:51:08 [cont-secrets] loading container secrets...
2024-05-31 16:51:08 [cont-secrets] container secrets loaded.
2024-05-31 16:51:08 [cont-init   ] executing container initialization scripts...
2024-05-31 16:51:08 [cont-init   ] 10-certs.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-certs.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-check-app-niceness.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-check-app-niceness.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-clean-logmonitor-states.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-clean-tmp-dir.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-fontconfig-cache-dir.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-init-users.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-init-users.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-nginx.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-nginx.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-openbox.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-openbox.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-pkgs-mirror.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-pkgs-mirror.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-set-tmp-dir-perms.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-set-tmp-dir-perms.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-vnc-password.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-vnc-password.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-web-data.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-web-data.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-x11-unix.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-x11-unix.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 10-xdg-runtime-dir.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 10-xdg-runtime-dir.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 15-cjk-font.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 15-cjk-font.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 15-install-pkgs.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 15-install-pkgs.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 85-take-config-ownership.sh: executing...
2024-05-31 16:51:08 [cont-init   ] 85-take-config-ownership.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] 89-info.sh: executing...
2024-05-31 16:51:08     ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
2024-05-31 16:51:08     │                                                                      │
2024-05-31 16:51:08     │ Application:           sticker-convert                               │
2024-05-31 16:51:08     │ Application Version:   n/a                                           │
2024-05-31 16:51:08     │ Docker Image Version:  n/a                                           │
2024-05-31 16:51:08     │ Docker Image Platform: linux/amd64                                   │
2024-05-31 16:51:08     │                                                                      │
2024-05-31 16:51:08     ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
2024-05-31 16:51:08 [cont-init   ] 89-info.sh: terminated successfully.
2024-05-31 16:51:08 [cont-init   ] all container initialization scripts executed.
2024-05-31 16:51:08 [init        ] giving control to process supervisor.
2024-05-31 16:51:08 [supervisor  ] loading services...
2024-05-31 16:51:08 [supervisor  ] loading service 'default'...
2024-05-31 16:51:08 [supervisor  ] loading service 'logmonitor'...
2024-05-31 16:51:08 [supervisor  ] service 'logmonitor' is disabled.
2024-05-31 16:51:08 [supervisor  ] loading service 'app'...
2024-05-31 16:51:08 [supervisor  ] loading service 'gui'...
2024-05-31 16:51:08 [supervisor  ] loading service 'xvnc'...
2024-05-31 16:51:08 [supervisor  ] loading service 'nginx'...
2024-05-31 16:51:08 [supervisor  ] loading service 'certsmonitor'...
2024-05-31 16:51:08 [supervisor  ] service 'certsmonitor' is disabled.
2024-05-31 16:51:08 [supervisor  ] loading service 'openbox'...
2024-05-31 16:51:08 [supervisor  ] loading service 'logrotate'...
2024-05-31 16:51:08 [supervisor  ] all services loaded.
2024-05-31 16:51:08 [supervisor  ] starting services...
2024-05-31 16:51:08 [supervisor  ] starting service 'xvnc'...
2024-05-31 16:51:08 [xvnc        ] Xvnc TigerVNC 1.13.1 - built Dec 21 2023 00:44:57
2024-05-31 16:51:08 [xvnc        ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
2024-05-31 16:51:08 [xvnc        ] See https://www.tigervnc.org for information on TigerVNC.
2024-05-31 16:51:08 [xvnc        ] Underlying X server release 12014000
2024-05-31 16:51:08 [xvnc        ] Fri May 31 08:51:08 2024
2024-05-31 16:51:08 [xvnc        ]  vncext:      VNC extension running!
2024-05-31 16:51:08 [xvnc        ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
2024-05-31 16:51:08 [xvnc        ]  vncext:      Listening for VNC connections on all interface(s), port 5900
2024-05-31 16:51:08 [xvnc        ]  vncext:      created VNC server for screen 0
2024-05-31 16:51:08 [supervisor  ] starting service 'nginx'...
2024-05-31 16:51:08 [nginx       ] Listening for HTTP connections on port 5800.
2024-05-31 16:51:09 [supervisor  ] starting service 'openbox'...
2024-05-31 16:51:09 [supervisor  ] starting service 'app'...
2024-05-31 16:51:09 [app         ] sticker-convert 2.8.11
2024-05-31 16:51:09 [app         ] Launching GUI...
2024-05-31 16:51:10 [supervisor  ] all services started.
2024-05-31 16:51:10 [app         ] Traceback (most recent call last):
2024-05-31 16:51:10 [app         ]   File "/app/sticker-convert.py", line 6, in <module>
2024-05-31 16:51:10 [app         ]     main()
2024-05-31 16:51:10 [app         ]   File "/app/sticker_convert/__main__.py", line 14, in main
2024-05-31 16:51:10 [app         ]     from sticker_convert.gui import GUI
2024-05-31 16:51:10 [app         ]   File "/app/sticker_convert/gui.py", line 29, in <module>
2024-05-31 16:51:10 [app         ]     from sticker_convert.job import Job
2024-05-31 16:51:10 [app         ]   File "/app/sticker_convert/job.py", line 17, in <module>
2024-05-31 16:51:10 [app         ]     from sticker_convert.downloaders.download_signal import DownloadSignal
2024-05-31 16:51:10 [app         ]   File "/app/sticker_convert/downloaders/download_signal.py", line 6, in <module>
2024-05-31 16:51:10 [app         ]     from signalstickers_client.errors import SignalException
2024-05-31 16:51:10 [app         ]   File "/usr/local/lib/python3.9/dist-packages/signalstickers_client/__init__.py", line 1, in <module>
2024-05-31 16:51:10 [app         ]     from .stickersclient import StickersClient  # type: ignore
2024-05-31 16:51:10 [app         ]   File "/usr/local/lib/python3.9/dist-packages/signalstickers_client/stickersclient.py", line 37, in <module>
2024-05-31 16:51:10 [app         ]     class StickersClient:
2024-05-31 16:51:10 [app         ]   File "/usr/local/lib/python3.9/dist-packages/signalstickers_client/stickersclient.py", line 49, in StickersClient
2024-05-31 16:51:10 [app         ]     exc_type: type[BaseException] | None = None,
2024-05-31 16:51:10 [app         ] TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
2024-05-31 16:51:11 [supervisor  ] service 'app' exited (with status 1).
2024-05-31 16:51:11 [supervisor  ] service 'app' exited, shutting down...
2024-05-31 16:51:11 [supervisor  ] stopping service 'openbox'...
2024-05-31 16:51:11 [supervisor  ] service 'openbox' exited (with status 0).
2024-05-31 16:51:11 [supervisor  ] stopping service 'nginx'...
2024-05-31 16:51:11 [supervisor  ] service 'nginx' exited (with status 0).
2024-05-31 16:51:11 [supervisor  ] stopping service 'xvnc'...
2024-05-31 16:51:11 [xvnc        ] Fri May 31 08:51:11 2024
2024-05-31 16:51:11 [xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
2024-05-31 16:51:11 [xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
2024-05-31 16:51:11 [supervisor  ] service 'xvnc' exited (with status 0).
2024-05-31 16:51:11 [finish      ] executing container finish scripts...
2024-05-31 16:51:11 [finish      ] all container finish scripts executed.
2024-05-31 16:51:24 [init        ] container is starting...
2024-05-31 16:51:24 [cont-env    ] loading container environment variables...
2024-05-31 16:51:24 [cont-env    ] APP_NAME: loading...
2024-05-31 16:51:24 [cont-env    ] DISPLAY: executing...
2024-05-31 16:51:24 [cont-env    ] DISPLAY: terminated successfully.
2024-05-31 16:51:24 [cont-env    ] DISPLAY: loading...
2024-05-31 16:51:24 [cont-env    ] DOCKER_IMAGE_PLATFORM: loading...
2024-05-31 16:51:24 [cont-env    ] GTK2_RC_FILES: executing...
2024-05-31 16:51:24 [cont-env    ] GTK2_RC_FILES: terminated successfully.
2024-05-31 16:51:24 [cont-env    ] GTK2_RC_FILES: loading...
2024-05-31 16:51:24 [cont-env    ] GTK_THEME: executing...
2024-05-31 16:51:24 [cont-env    ] GTK_THEME: terminated successfully.
2024-05-31 16:51:24 [cont-env    ] GTK_THEME: loading...
2024-05-31 16:51:24 [cont-env    ] HOME: loading...
2024-05-31 16:51:24 [cont-env    ] QT_STYLE_OVERRIDE: executing...
2024-05-31 16:51:24 [cont-env    ] QT_STYLE_OVERRIDE: terminated successfully.
2024-05-31 16:51:24 [cont-env    ] QT_STYLE_OVERRIDE: loading...
2024-05-31 16:51:24 [cont-env    ] TAKE_CONFIG_OWNERSHIP: loading...
2024-05-31 16:51:24 [cont-env    ] XDG_CACHE_HOME: loading...
2024-05-31 16:51:24 [cont-env    ] XDG_CONFIG_HOME: loading...
2024-05-31 16:51:24 [cont-env    ] XDG_DATA_HOME: loading...
2024-05-31 16:51:24 [cont-env    ] XDG_RUNTIME_DIR: loading...
2024-05-31 16:51:24 [cont-env    ] XDG_STATE_HOME: loading...
2024-05-31 16:51:24 [cont-env    ] container environment variables initialized.
2024-05-31 16:51:24 [cont-secrets] loading container secrets...
2024-05-31 16:51:24 [cont-secrets] container secrets loaded.
2024-05-31 16:51:24 [cont-init   ] executing container initialization scripts...
2024-05-31 16:51:24 [cont-init   ] 10-certs.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-certs.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-check-app-niceness.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-check-app-niceness.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-clean-logmonitor-states.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-clean-logmonitor-states.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-clean-tmp-dir.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-clean-tmp-dir.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-fontconfig-cache-dir.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-fontconfig-cache-dir.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-init-users.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-init-users.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-nginx.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-nginx.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-openbox.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-openbox.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-pkgs-mirror.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-pkgs-mirror.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-set-tmp-dir-perms.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-set-tmp-dir-perms.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-vnc-password.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-vnc-password.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-web-data.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-web-data.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-x11-unix.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-x11-unix.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 10-xdg-runtime-dir.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 10-xdg-runtime-dir.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 15-cjk-font.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 15-cjk-font.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 15-install-pkgs.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 15-install-pkgs.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 85-take-config-ownership.sh: executing...
2024-05-31 16:51:24 [cont-init   ] 85-take-config-ownership.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] 89-info.sh: executing...
2024-05-31 16:51:24     ╭――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╮
2024-05-31 16:51:24     │                                                                      │
2024-05-31 16:51:24     │ Application:           sticker-convert                               │
2024-05-31 16:51:24     │ Application Version:   n/a                                           │
2024-05-31 16:51:24     │ Docker Image Version:  n/a                                           │
2024-05-31 16:51:24     │ Docker Image Platform: linux/amd64                                   │
2024-05-31 16:51:24     │                                                                      │
2024-05-31 16:51:24     ╰――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――╯
2024-05-31 16:51:24 [cont-init   ] 89-info.sh: terminated successfully.
2024-05-31 16:51:24 [cont-init   ] all container initialization scripts executed.
2024-05-31 16:51:24 [init        ] giving control to process supervisor.
2024-05-31 16:51:24 [supervisor  ] loading services...
2024-05-31 16:51:24 [supervisor  ] loading service 'default'...
2024-05-31 16:51:24 [supervisor  ] loading service 'logmonitor'...
2024-05-31 16:51:24 [supervisor  ] service 'logmonitor' is disabled.
2024-05-31 16:51:24 [supervisor  ] loading service 'app'...
2024-05-31 16:51:24 [supervisor  ] loading service 'gui'...
2024-05-31 16:51:24 [supervisor  ] loading service 'xvnc'...
2024-05-31 16:51:24 [supervisor  ] loading service 'nginx'...
2024-05-31 16:51:24 [supervisor  ] loading service 'certsmonitor'...
2024-05-31 16:51:24 [supervisor  ] service 'certsmonitor' is disabled.
2024-05-31 16:51:24 [supervisor  ] loading service 'openbox'...
2024-05-31 16:51:24 [supervisor  ] loading service 'logrotate'...
2024-05-31 16:51:24 [supervisor  ] all services loaded.
2024-05-31 16:51:24 [supervisor  ] starting services...
2024-05-31 16:51:24 [supervisor  ] starting service 'xvnc'...
2024-05-31 16:51:24 [xvnc        ] Xvnc TigerVNC 1.13.1 - built Dec 21 2023 00:44:57
2024-05-31 16:51:24 [xvnc        ] Copyright (C) 1999-2022 TigerVNC Team and many others (see README.rst)
2024-05-31 16:51:24 [xvnc        ] See https://www.tigervnc.org for information on TigerVNC.
2024-05-31 16:51:24 [xvnc        ] Underlying X server release 12014000
2024-05-31 16:51:24 [xvnc        ] Fri May 31 08:51:24 2024
2024-05-31 16:51:24 [xvnc        ]  vncext:      VNC extension running!
2024-05-31 16:51:24 [xvnc        ]  vncext:      Listening for VNC connections on /tmp/vnc.sock (mode 0660)
2024-05-31 16:51:24 [xvnc        ]  vncext:      Listening for VNC connections on all interface(s), port 5900
2024-05-31 16:51:24 [xvnc        ]  vncext:      created VNC server for screen 0
2024-05-31 16:51:25 [supervisor  ] starting service 'nginx'...
2024-05-31 16:51:25 [nginx       ] Listening for HTTP connections on port 5800.
2024-05-31 16:51:25 [supervisor  ] starting service 'openbox'...
2024-05-31 16:51:26 [supervisor  ] starting service 'app'...
2024-05-31 16:51:26 [app         ] sticker-convert 2.8.11
2024-05-31 16:51:26 [app         ] Launching GUI...
2024-05-31 16:51:26 [app         ] Traceback (most recent call last):
2024-05-31 16:51:26 [app         ]   File "/app/sticker-convert.py", line 6, in <module>
2024-05-31 16:51:26 [app         ]     main()
2024-05-31 16:51:26 [app         ]   File "/app/sticker_convert/__main__.py", line 14, in main
2024-05-31 16:51:26 [app         ]     from sticker_convert.gui import GUI
2024-05-31 16:51:26 [app         ]   File "/app/sticker_convert/gui.py", line 29, in <module>
2024-05-31 16:51:26 [app         ]     from sticker_convert.job import Job
2024-05-31 16:51:26 [app         ]   File "/app/sticker_convert/job.py", line 17, in <module>
2024-05-31 16:51:26 [app         ]     from sticker_convert.downloaders.download_signal import DownloadSignal
2024-05-31 16:51:26 [app         ]   File "/app/sticker_convert/downloaders/download_signal.py", line 6, in <module>
2024-05-31 16:51:26 [app         ]     from signalstickers_client.errors import SignalException
2024-05-31 16:51:26 [app         ]   File "/usr/local/lib/python3.9/dist-packages/signalstickers_client/__init__.py", line 1, in <module>
2024-05-31 16:51:26 [app         ]     from .stickersclient import StickersClient  # type: ignore
2024-05-31 16:51:26 [app         ]   File "/usr/local/lib/python3.9/dist-packages/signalstickers_client/stickersclient.py", line 37, in <module>
2024-05-31 16:51:26 [app         ]     class StickersClient:
2024-05-31 16:51:26 [app         ]   File "/usr/local/lib/python3.9/dist-packages/signalstickers_client/stickersclient.py", line 49, in StickersClient
2024-05-31 16:51:26 [app         ]     exc_type: type[BaseException] | None = None,
2024-05-31 16:51:26 [app         ] TypeError: unsupported operand type(s) for |: 'types.GenericAlias' and 'NoneType'
2024-05-31 16:51:26 [supervisor  ] all services started.
2024-05-31 16:51:27 [supervisor  ] service 'app' exited (with status 1).
2024-05-31 16:51:27 [supervisor  ] service 'app' exited, shutting down...
2024-05-31 16:51:27 [supervisor  ] stopping service 'openbox'...
2024-05-31 16:51:27 [supervisor  ] service 'openbox' exited (with status 0).
2024-05-31 16:51:27 [supervisor  ] stopping service 'nginx'...
2024-05-31 16:51:27 [supervisor  ] service 'nginx' exited (with status 0).
2024-05-31 16:51:28 [supervisor  ] stopping service 'xvnc'...
2024-05-31 16:51:28 [xvnc        ] Fri May 31 08:51:28 2024
2024-05-31 16:51:28 [xvnc        ]  ComparingUpdateTracker: 0 pixels in / 0 pixels out
2024-05-31 16:51:28 [xvnc        ]  ComparingUpdateTracker: (1:-nan ratio)
2024-05-31 16:51:28 [supervisor  ] service 'xvnc' exited (with status 0).
2024-05-31 16:51:28 [finish      ] executing container finish scripts...
2024-05-31 16:51:28 [finish      ] all container finish scripts executed.

```

**Comment by laggykiller** [comment]
Should be fixed, please pull the newest version and try again

**Comment by laggykiller** [comment]
Closing as it should be fixed and no reply.
