### ISSUE TITLE
MacOS error

### ISSUE THREAD

**Issue by landownn** [laggykiller/sticker-convert#162]
Hey! I’ve attempted to open sticker-convert on MacOS Sonoma 14.5 (M1 chip) and I get

`Last login: Thu Jun  6 12:10:59 on ttys000
/Applications/sticker-convert.app/Contents/MacOS/sticker-convert-cli ; exit;
myname@MacBook-Air-Name ~ % /Applications/sticker-convert.app/Contents/MacOS/sticker-convert-cli ; exit;
sticker-convert 2.8.13
Launching GUI...
Traceback (most recent call last):
  File "/Applications/sticker-convert.app/Contents/MacOS/sticker-convert.py", line 6, in <module>
  File "/Applications/sticker-convert.app/Contents/MacOS/sticker_convert/__main__.py", line 14, in main
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Applications/sticker-convert.app/Contents/MacOS/sticker_convert/gui.py", line 29, in <module sticker_convert.gui>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Applications/sticker-convert.app/Contents/MacOS/sticker_convert/job.py", line 15, in <module sticker_convert.job>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Applications/sticker-convert.app/Contents/MacOS/sticker_convert/downloaders/download_kakao.py", line 12, in <module sticker_convert.downloaders.download_kakao>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Applications/sticker-convert.app/Contents/MacOS/js2py/__init__.py", line 72, in <module js2py>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "/Applications/sticker-convert.app/Contents/MacOS/js2py/base.py", line 3007, in <module js2py.base>
  File "/Applications/sticker-convert.app/Contents/MacOS/js2py/base.py", line 2986, in define_error_type
  File "/Applications/sticker-convert.app/Contents/MacOS/js2py/base.py", line 165, in Js
  File "/Applications/sticker-convert.app/Contents/MacOS/js2py/base.py", line 1377, in __init__
  File "/Applications/sticker-convert.app/Contents/MacOS/js2py/utils/injector.py", line 29, in fix_js_args
TypeError: arg 5 (closure) expected cell, found compiled_cell

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Proces zakończony]`

Even though I’ve Python library and nothing helps.

Thanks

**Comment by laggykiller** [comment]
Fixed, please try 2.8.14
