### ISSUE TITLE
Unable to download Kakao stickers, Windows GUI

### ISSUE THREAD

**Issue by deadnalive** [laggykiller/sticker-convert#189]
```
Skip moving old files in input directory as input source is empty
Skip moving old files in output directory as no_compress is True
Downloading...
##### EXCEPTION #####
Function: <compiled_function DownloadKakao.start at 0x00000161CFAD0740>
Arguments: ['https://e.kakao.com/t/sues-sue-per-week', WindowsPath('C:/STICKER/sticker-convert/stickers_input'), 'CredOption(REDACTED)']
Traceback (most recent call last):
  File "C:\STICKER\STICKE~1\sticker_convert\job.py", line 120, in worker
  File "C:\STICKER\STICKE~1\sticker_convert\downloaders\download_kakao.py", line 336, in start
  File "C:\STICKER\STICKE~1\sticker_convert\downloaders\download_kakao.py", line 187, in download_stickers_kakao
  File "C:\STICKER\STICKE~1\sticker_convert\downloaders\download_kakao.py", line 59, in get_item_code
IndexError: list index out of range
#####################
no_compress is set to True, skip compression
Input directory is empty, nothing to copy to output directory
Saving to local directory only, nothing to export
##########
Summary:
##########

Export result: None
```

I've inputted my Kakao auth key correctly, but this error happens.

**Comment by laggykiller** [comment]
You should use method 1: https://github.com/laggykiller/sticker-convert/blob/master/docs/guide_kakao.md
