### ISSUE TITLE
ReferenceError: document is not defined 

### ISSUE THREAD

**Issue by racotokki** [laggykiller/sticker-convert#237]
try to download stickers from kakao,but it comes out with this error

The progress:

Skip moving old files in input directory as input source is empty
Skip moving old files in output directory as no_compress is True
Downloading...
##### EXCEPTION #####
Function: <compiled_function DownloadKakao.start at 0x000002126406A540>
Arguments: [InputOption(option='kakao', url='https://emoticon.kakao.com/items/0rwXEXbJ9f8MJQv31VXc21zlDq8=?lang=zh_TW_#Hant&referer=share_link', dir=WindowsPath('D:/Video Decrypt/sticker-convert-windows-x86_64/sticker-convert/stickers_input')), 'CredOption(REDACTED)']
Traceback (most recent call last):
  File "D:\VIDEOD~1\STICKE~1\STICKE~1\sticker_convert\job.py", line 121, in worker
  File "D:\VIDEOD~1\STICKE~1\STICKE~1\sticker_convert\downloaders\download_kakao.py", line 339, in start
  File "D:\VIDEOD~1\STICKE~1\STICKE~1\sticker_convert\downloaders\download_kakao.py", line 144, in download_stickers_kakao
  File "D:\VIDEOD~1\STICKE~1\STICKE~1\sticker_convert\downloaders\download_kakao.py", line 133, in get_info_from_share_link
  File "D:\VIDEOD~1\STICKE~1\STICKE~1\py_mini_racer\_mini_racer.py", line 128, in eval
  File "D:\VIDEOD~1\STICKE~1\STICKE~1\py_mini_racer\_context.py", line 134, in evaluate
  File "D:\VIDEOD~1\STICKE~1\STICKE~1\py_mini_racer\_sync_future.py", line 33, in get
py_mini_racer._types.JSEvalException: <anonymous>:26: ReferenceError: document is not defined
}                for (var anchors = document.querySelectorAll("button.to_launch"), i = 0; i < anchors.length; i++)
                                    ^

ReferenceError: document is not defined
    at <anonymous>:26:37

#####################
no_compress is set to True, skip compression
Output directory is not empty, not copying files from input directory
Saving to local directory only, nothing to export
##########
Summary:
##########

Export result: None

Is there any solution?Always thank you for your hard work!

**Comment by sidsidanf** [comment]
저도 똑같은 오류가 나오는데 해결방법이 있나요?

**Comment by laggykiller** [comment]
Thanks for reporting, fixed in v2.10.9
