### ISSUE TITLE
Local Convertion from whatsapp stickers to Telegram [Error]

### ISSUE THREAD

**Issue by Milor123** [laggykiller/sticker-convert#26]
I am trying convert files  **`.webp`** from sticker whatsapp pack to Telegram, but i get this error on shell
I am in windows 11 with AMD GPU

```shel
Launching GUI...
Nothing to download
Compressing...
[I] Start compressing sticker_1.webm -> sticker_1.tgs
[I] Start compressing sticker_10.webm -> sticker_10.tgs
[I] Start compressing sticker_11.webm -> sticker_11.tgs
[I] Start compressing sticker_12.webm -> sticker_12.tgs
[I] Start compressing sticker_13.webm -> sticker_13.tgs
[I] Start compressing sticker_14.webm -> sticker_14.tgs
[I] Start compressing sticker_15.webm -> sticker_15.tgs
[I] Start compressing sticker_16.webm -> sticker_16.tgs
[C] Compressing sticker_1.webm -> sticker_1.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
[C] Compressing sticker_10.webm -> sticker_10.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
[C] Compressing sticker_11.webm -> sticker_11.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
[C] Compressing sticker_12.webm -> sticker_12.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
[C] Compressing sticker_13.webm -> sticker_13.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
[C] Compressing sticker_14.webm -> sticker_14.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
[C] Compressing sticker_15.webm -> sticker_15.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
[C] Compressing sticker_16.webm -> sticker_16.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
Unknown importer
Exception in thread Thread-22 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "flow.py", line 312, in compress_thread
  File "utils\converter.py", line 40, in convert_and_compress_to_size
  File "utils\converter.py", line 111, in compress_to_size
  File "<frozen genericpath>", line 50, in getsize
FileNotFoundError: [WinError 2] El sistema no puede encontrar el archivo especificado: 'C:\\Temp\\tmp_zmirtci\\0.tgs'
[I] Start compressing sticker_17.webm -> sticker_17.tgs
[C] Compressing sticker_17.webm -> sticker_17.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
Exception in thread Thread-27 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "flow.py", line 312, in compress_thread
  File "utils\converter.py", line 40, in convert_and_compress_to_size
  File "utils\converter.py", line 107, in compress_to_size
  File "utils\converter.py", line 403, in convert_lottie
  File "utils\lottie_convert.py", line 85, in lottie_convert
  File "lottie\parsers\baseporter.py", line 18, in process
TypeError: export_tgs() got an unexpected keyword argument 'bmp-mode'
[I] Start compressing sticker_18.webm -> sticker_18.tgs
[C] Compressing sticker_18.webm -> sticker_18.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
Exception in thread Thread-17 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "flow.py", line 312, in compress_thread
  File "utils\converter.py", line 40, in convert_and_compress_to_size
  File "utils\converter.py", line 107, in compress_to_size
  File "utils\converter.py", line 403, in convert_lottie
  File "utils\lottie_convert.py", line 85, in lottie_convert
  File "lottie\parsers\baseporter.py", line 18, in process
TypeError: export_tgs() got an unexpected keyword argument 'bmp-mode'
[I] Start compressing sticker_19.webm -> sticker_19.tgs
[C] Compressing sticker_19.webm -> sticker_19.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
Exception in thread Thread-32 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "flow.py", line 312, in compress_thread
  File "utils\converter.py", line 40, in convert_and_compress_to_size
  File "utils\converter.py", line 107, in compress_to_size
  File "utils\converter.py", line 403, in convert_lottie
  File "utils\lottie_convert.py", line 85, in lottie_convert
  File "lottie\parsers\baseporter.py", line 18, in process
TypeError: export_tgs() got an unexpected keyword argument 'bmp-mode'
[I] Start compressing sticker_2.webm -> sticker_2.tgs
Exception in thread Thread-12 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
[C] Compressing sticker_2.webm -> sticker_2.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
  File "flow.py", line 312, in compress_thread
  File "utils\converter.py", line 40, in convert_and_compress_to_size
  File "utils\converter.py", line 107, in compress_to_size
  File "utils\converter.py", line 403, in convert_lottie
  File "utils\lottie_convert.py", line 85, in lottie_convert
  File "lottie\parsers\baseporter.py", line 18, in process
TypeError: export_tgs() got an unexpected keyword argument 'bmp-mode'
[I] Start compressing sticker_20.webm -> sticker_20.tgs
[C] Compressing sticker_20.webm -> sticker_20.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
Exception in thread Thread-47 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "flow.py", line 312, in compress_thread
  File "utils\converter.py", line 40, in convert_and_compress_to_size
  File "utils\converter.py", line 107, in compress_to_size
  File "utils\converter.py", line 403, in convert_lottie
  File "utils\lottie_convert.py", line 85, in lottie_convert
  File "lottie\parsers\baseporter.py", line 18, in process
TypeError: export_tgs() got an unexpected keyword argument 'bmp-mode'
[I] Start compressing sticker_21.webm -> sticker_21.tgs
[C] Compressing sticker_21.webm -> sticker_21.tgs res=512x512, quality=100, fps=60, color=257 (step 0-0-1)
Exception in thread Thread-42 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "flow.py", line 312, in compress_thread
  File "utils\converter.py", line 40, in convert_and_compress_to_size
  File "utils\converter.py", line 107, in compress_to_size
  File "utils\converter.py", line 403, in convert_lottie
  File "utils\lottie_convert.py", line 85, in lottie_convert
  File "lottie\parsers\baseporter.py", line 18, in process
TypeError: export_tgs() got an unexpected keyword argument 'bmp-mode'
```

**Comment by laggykiller** [comment]
Please choose `telegram` as compression preset instead of `telegram_vector`. I should add a warning about this...

**Comment by laggykiller** [comment]
Added warning in v1.15.2
