### ISSUE TITLE
Issues converting stickers from Telegram to iMessage

### ISSUE THREAD

**Issue by piroko13** [laggykiller/sticker-convert#41]
I'm getting the following error when trying to convert a Telegram sticker from a local directory to iMessage sticker. Happens when using all three compression options for iMessage on both Windows and Mac.

Exception in thread Thread-3 (start_process):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "gui.py", line 348, in start_process
  File "flow.py", line 58, in start
  File "flow.py", line 356, in export
  File "uploaders\xcode_imessage.py", line 127, in create_imessage_xcode
  File "utils\converter.py", line 40, in convert_and_compress_to_size
  File "utils\converter.py", line 108, in compress_to_size
  File "utils\converter.py", line 427, in convert_to_apng_anim
  File "utils\converter.py", line 262, in convert_generic_anim
  File "utils\converter.py", line 242, in convert_generic_anim
TypeError: '<' not supported between instances of 'float' and 'str'

**Comment by laggykiller** [comment]
Fixed in v1.18.0. Please check.

**Comment by piroko13** [comment]
Thank you, it works now.
