### ISSUE TITLE
[Windows] Unable to upload stickers to signal

### ISSUE THREAD

**Issue by Zakor11** [laggykiller/sticker-convert#60]
<h2>Bug Description</h2>

Unable to upload stickers to signal, due to Python UnboundLocalError: cannot access local variable 'spec_choice' where it is not associated with a value.
Tried the process with downloading from telegram first and with using downloaded stickers to upload.

Disclaimer: Tested only with a telegram non-animated stickerset

<h2>Console Output</h2>

```
[Completed Downloading and Compression]
Exporting...
Verifying C:\Users\Zakor\Desktop\sticker-convert\stickers_output\000.webp for uploading to signal
Exception in thread Thread-1 (start_process):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "gui.py", line 374, in start_process
  File "flow.py", line 64, in start
  File "flow.py", line 383, in export
  File "uploaders\upload_signal.py", line 134, in start
  File "uploaders\upload_signal.py", line 123, in upload_stickers_signal
  File "uploaders\upload_signal.py", line 85, in add_stickers_to_pack
UnboundLocalError: cannot access local variable 'spec_choice' where it is not associated with a value
```

<h2>Environment</h2>
OS: Windows 10 Pro 22H2

Sticker convert version: v2.0.15

**Comment by laggykiller** [comment]
Thanks for your report. Should be fixed in v2.0.16, please check!
