### ISSUE TITLE
Converting APNG to TGS gives an Error in ffmpeg. And can't click the START button without downscaling.

### ISSUE THREAD

**Issue by ACHIYA96** [laggykiller/sticker-convert#8]
Launching GUI...
Exception in thread Thread-21 (compress_thread):
Exception in thread Thread-11 (compress_thread):
Exception in thread Thread-6 (compress_thread):
Traceback (most recent call last):
Exception in thread Thread-16 (compress_thread):
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "threading.py", line 975, in run
  File "flow.py", line 289, in compress_thread
  File "threading.py", line 975, in run
  File "flow.py", line 289, in compress_thread
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "flow.py", line 289, in compress_thread
  File "flow.py", line 289, in compress_thread
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 237, in convert_generic_anim
  File "utils\converter.py", line 237, in convert_generic_anim
  File "utils\converter.py", line 237, in convert_generic_anim
  File "utils\converter.py", line 237, in convert_generic_anim
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "ffmpeg\_run.py", line 325, in run
  File "ffmpeg\_run.py", line 325, in run
  File "ffmpeg\_run.py", line 325, in run
  File "ffmpeg\_run.py", line 325, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
Exception in thread Thread-26 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
Exception in thread Thread-41 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "threading.py", line 975, in run
Exception in thread Thread-36 (compress_thread):
  File "flow.py", line 289, in compress_thread
Traceback (most recent call last):
  File "flow.py", line 289, in compress_thread
  File "threading.py", line 1038, in _bootstrap_inner
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "threading.py", line 975, in run
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 237, in convert_generic_anim
  File "flow.py", line 289, in compress_thread
  File "utils\converter.py", line 237, in convert_generic_anim
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "ffmpeg\_run.py", line 325, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
  File "utils\converter.py", line 99, in compress_to_size
  File "ffmpeg\_run.py", line 325, in run
  File "utils\converter.py", line 237, in convert_generic_anim
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
Exception in thread Thread-31 (compress_thread):
Traceback (most recent call last):
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "threading.py", line 1038, in _bootstrap_inner
  File "ffmpeg\_run.py", line 325, in run
  File "threading.py", line 975, in run
  File "flow.py", line 289, in compress_thread
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 237, in convert_generic_anim
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "ffmpeg\_run.py", line 325, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
Exception in thread Thread-46 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "flow.py", line 289, in compress_thread
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 237, in convert_generic_anim
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "ffmpeg\_run.py", line 325, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
Exception in thread Thread-61 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "flow.py", line 289, in compress_thread
  File "utils\converter.py", line 35, in convert_and_compress_to_size
Exception in thread Thread-56 (compress_thread):
Traceback (most recent call last):
Exception in thread Thread-51 (compress_thread):
  File "threading.py", line 1038, in _bootstrap_inner
  File "utils\converter.py", line 99, in compress_to_size
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "utils\converter.py", line 237, in convert_generic_anim
  File "threading.py", line 975, in run
  File "flow.py", line 289, in compress_thread
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "flow.py", line 289, in compress_thread
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "ffmpeg\_run.py", line 325, in run
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 35, in convert_and_compress_to_size
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
  File "utils\converter.py", line 237, in convert_generic_anim
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "utils\converter.py", line 237, in convert_generic_anim
  File "ffmpeg\_run.py", line 325, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "ffmpeg\_run.py", line 325, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
Exception in thread Thread-66 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "flow.py", line 289, in compress_thread
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 237, in convert_generic_anim
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "ffmpeg\_run.py", line 325, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
Exception in thread Thread-71 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "flow.py", line 289, in compress_thread
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 237, in convert_generic_anim
Exception in thread Thread-81 (compress_thread):
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
Traceback (most recent call last):
  File "ffmpeg\_run.py", line 325, in run
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
  File "flow.py", line 289, in compress_thread
  File "utils\converter.py", line 35, in convert_and_compress_to_size
Exception in thread Thread-76 (compress_thread):
Traceback (most recent call last):
  File "utils\converter.py", line 99, in compress_to_size
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "utils\converter.py", line 237, in convert_generic_anim
  File "flow.py", line 289, in compress_thread
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "ffmpeg\_run.py", line 325, in run
  File "utils\converter.py", line 35, in convert_and_compress_to_size
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 237, in convert_generic_anim
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "ffmpeg\_run.py", line 325, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)
Exception in thread Thread-86 (compress_thread):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "flow.py", line 289, in compress_thread
  File "utils\converter.py", line 35, in convert_and_compress_to_size
  File "utils\converter.py", line 99, in compress_to_size
  File "utils\converter.py", line 237, in convert_generic_anim
  File "utils\converter.py", line 286, in convert_generic_anim_pymodule
  File "ffmpeg\_run.py", line 325, in run
ffmpeg._run.Error: ffmpeg error (see stderr output for detail)

**Comment by laggykiller** [comment]
You should not convert bitmap to tgs. It is intended for vector art (e.g. SVG). Convert to webm if you want to use on telegram

What is your screen resolution?

**Comment by ACHIYA96** [comment]
So we can't convert APNG to TGS?

I'm using 1360x768.

**Comment by laggykiller** [comment]
APNG is bitmap not vector, so please don't

I have made the whole window scrollable if you have small screen resolution. Check out v1.9.2
